name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: Ubuntu-20.04

    steps:

    - 
     name: Build the Docker image     
     uses: actions/checkout@v2
    -
     run: docker buildx . --file Dockerfile --tag alluxio:latest
