name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - 
     uses: docker/setup-qemu-action@v1.0.1
     with:
       platforms: amd64, arm64
    - 
     name: Build the Docker image     
     uses: actions/checkout@v2
    -
     run: docker buildx . --file Dockerfile --tag alluxio:latest
