name: Docker Image CI

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Push to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.ALLUXIO_TOKEN }}
        #registry: docker.pkg.github.com
        registry: ghcr.io
        repository: angzam78/alluxio
        tag_with_ref: true
        
